image: gcc:latest
stages:
  - build

build-c:
  stage: build
  script:
    - cd c; make
  artifacts:
    paths:
      - libcmdlineoptions.*
      - tests-*

test-c:
  stage: test
  script:
    - cd c; make test
  dependencies:
    - build-c
