stages:
  - build

build-c:
  image: archlinux_gcc53_qt5_cmake
  stage: build
  script:
    - cd c; make
  artifacts:
    paths:
      - c/libcmdlineoptions.*
      - c/tests-*

build-java:
  image: archlinux_jdk8
  stage: build


#test-c:
  #stage: test
  #script:
    #- cd c; make test
  #dependencies:
    #- build-c
