image: gcc:latest
stages:
  - build
  - test

build-c:
  stage: build
  script:
    - cd c; make
  artifacts:
    - libcmdlineoptions.*
    - tests-*

test-c:
  stage: test
  script:
    - cd c; make test
  dependencies:
    - build-c
